# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/predict.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/predict.proto\x12\x07predict\"\xbf\x01\n\x11PredictionRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12:\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32(.predict.PredictionRequest.FeaturesEntry\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\xaf\x01\n\x12PredictionResponse\x12\x12\n\nprediction\x18\x01 \x01(\x05\x12\x15\n\rprobabilities\x18\x02 \x03(\x02\x12\x1a\n\x12model_version_used\x18\x03 \x01(\t\x12\x12\n\nlatency_ms\x18\x04 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x05 \x01(\x05\x12\x15\n\rerror_message\x18\x06 \x01(\t\x12\x12\n\nrequest_id\x18\x07 \x01(\t\"\x0f\n\rHealthRequest\"7\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rloaded_models\x18\x02 \x03(\t2\x97\x01\n\x11PredictionService\x12\x42\n\x07Predict\x12\x1a.predict.PredictionRequest\x1a\x1b.predict.PredictionResponse\x12>\n\x0bHealthCheck\x12\x16.predict.HealthRequest\x1a\x17.predict.HealthResponseB#Z!driftline/proto/predict;predictpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!driftline/proto/predict;predictpb'
  _globals['_PREDICTIONREQUEST_FEATURESENTRY']._loaded_options = None
  _globals['_PREDICTIONREQUEST_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTIONREQUEST']._serialized_start=33
  _globals['_PREDICTIONREQUEST']._serialized_end=224
  _globals['_PREDICTIONREQUEST_FEATURESENTRY']._serialized_start=177
  _globals['_PREDICTIONREQUEST_FEATURESENTRY']._serialized_end=224
  _globals['_PREDICTIONRESPONSE']._serialized_start=227
  _globals['_PREDICTIONRESPONSE']._serialized_end=402
  _globals['_HEALTHREQUEST']._serialized_start=404
  _globals['_HEALTHREQUEST']._serialized_end=419
  _globals['_HEALTHRESPONSE']._serialized_start=421
  _globals['_HEALTHRESPONSE']._serialized_end=476
  _globals['_PREDICTIONSERVICE']._serialized_start=479
  _globals['_PREDICTIONSERVICE']._serialized_end=630
# @@protoc_insertion_point(module_scope)
