# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import predict_pb2 as proto_dot_predict__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/predict_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PredictionServiceStub:
    """PredictionService is the internal contract between the Go control plane
    (client) and the Python ml-service (server). Every prediction goes through it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/predict.PredictionService/Predict',
                request_serializer=proto_dot_predict__pb2.PredictionRequest.SerializeToString,
                response_deserializer=proto_dot_predict__pb2.PredictionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/predict.PredictionService/HealthCheck',
                request_serializer=proto_dot_predict__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_predict__pb2.HealthResponse.FromString,
                _registered_method=True)


class PredictionServiceServicer:
    """PredictionService is the internal contract between the Go control plane
    (client) and the Python ml-service (server). Every prediction goes through it.
    """

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=proto_dot_predict__pb2.PredictionRequest.FromString,
                    response_serializer=proto_dot_predict__pb2.PredictionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_predict__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_predict__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'predict.PredictionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('predict.PredictionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictionService:
    """PredictionService is the internal contract between the Go control plane
    (client) and the Python ml-service (server). Every prediction goes through it.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/predict.PredictionService/Predict',
            proto_dot_predict__pb2.PredictionRequest.SerializeToString,
            proto_dot_predict__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/predict.PredictionService/HealthCheck',
            proto_dot_predict__pb2.HealthRequest.SerializeToString,
            proto_dot_predict__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
