// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: predict.proto

package predictpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                                          // e.g. "loan_default_xgb"
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`                                                 // e.g. "v1"
	Features      map[string]float64     `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // encoded feature name -> value (see feature_schema.json)
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                          // caller-generated id, echoed back for log correlation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictionRequest) Reset() {
	*x = PredictionRequest{}
	mi := &file_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionRequest) ProtoMessage() {}

func (x *PredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionRequest.ProtoReflect.Descriptor instead.
func (*PredictionRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{0}
}

func (x *PredictionRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *PredictionRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *PredictionRequest) GetFeatures() map[string]float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PredictionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PredictionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Prediction       int32                  `protobuf:"varint,1,opt,name=prediction,proto3" json:"prediction,omitempty"`               // class label (0 = no default, 1 = default)
	Probabilities    []float32              `protobuf:"fixed32,2,rep,packed,name=probabilities,proto3" json:"probabilities,omitempty"` // per-class probabilities, index == class label
	ModelVersionUsed string                 `protobuf:"bytes,3,opt,name=model_version_used,json=modelVersionUsed,proto3" json:"model_version_used,omitempty"`
	LatencyMs        int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`    // server-side inference latency
	StatusCode       int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 0 OK, otherwise a google.rpc.Code-style value
	ErrorMessage     string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RequestId        string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PredictionResponse) Reset() {
	*x = PredictionResponse{}
	mi := &file_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResponse) ProtoMessage() {}

func (x *PredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResponse.ProtoReflect.Descriptor instead.
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{1}
}

func (x *PredictionResponse) GetPrediction() int32 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

func (x *PredictionResponse) GetProbabilities() []float32 {
	if x != nil {
		return x.Probabilities
	}
	return nil
}

func (x *PredictionResponse) GetModelVersionUsed() string {
	if x != nil {
		return x.ModelVersionUsed
	}
	return ""
}

func (x *PredictionResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PredictionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PredictionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PredictionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_predict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                 // "SERVING" / "NOT_SERVING"
	LoadedModels  []string               `protobuf:"bytes,2,rep,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"` // "name/version" currently cached in memory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_predict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetLoadedModels() []string {
	if x != nil {
		return x.LoadedModels
	}
	return nil
}

var File_predict_proto protoreflect.FileDescriptor

const file_predict_proto_rawDesc = "" +
	"\n" +
	"\rpredict.proto\x12\apredict\"\xf9\x01\n" +
	"\x11PredictionRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12D\n" +
	"\bfeatures\x18\x03 \x03(\v2(.predict.PredictionRequest.FeaturesEntryR\bfeatures\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x8c\x02\n" +
	"\x12PredictionResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\x05R\n" +
	"prediction\x12$\n" +
	"\rprobabilities\x18\x02 \x03(\x02R\rprobabilities\x12,\n" +
	"\x12model_version_used\x18\x03 \x01(\tR\x10modelVersionUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\x0f\n" +
	"\rHealthRequest\"M\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rloaded_models\x18\x02 \x03(\tR\floadedModels2\x97\x01\n" +
	"\x11PredictionService\x12B\n" +
	"\aPredict\x12\x1a.predict.PredictionRequest\x1a\x1b.predict.PredictionResponse\x12>\n" +
	"\vHealthCheck\x12\x16.predict.HealthRequest\x1a\x17.predict.HealthResponseB#Z!driftline/proto/predict;predictpbb\x06proto3"

var (
	file_predict_proto_rawDescOnce sync.Once
	file_predict_proto_rawDescData []byte
)

func file_predict_proto_rawDescGZIP() []byte {
	file_predict_proto_rawDescOnce.Do(func() {
		file_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_predict_proto_rawDesc), len(file_predict_proto_rawDesc)))
	})
	return file_predict_proto_rawDescData
}

var file_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_predict_proto_goTypes = []any{
	(*PredictionRequest)(nil),  // 0: predict.PredictionRequest
	(*PredictionResponse)(nil), // 1: predict.PredictionResponse
	(*HealthRequest)(nil),      // 2: predict.HealthRequest
	(*HealthResponse)(nil),     // 3: predict.HealthResponse
	nil,                        // 4: predict.PredictionRequest.FeaturesEntry
}
var file_predict_proto_depIdxs = []int32{
	4, // 0: predict.PredictionRequest.features:type_name -> predict.PredictionRequest.FeaturesEntry
	0, // 1: predict.PredictionService.Predict:input_type -> predict.PredictionRequest
	2, // 2: predict.PredictionService.HealthCheck:input_type -> predict.HealthRequest
	1, // 3: predict.PredictionService.Predict:output_type -> predict.PredictionResponse
	3, // 4: predict.PredictionService.HealthCheck:output_type -> predict.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_predict_proto_init() }
func file_predict_proto_init() {
	if File_predict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_predict_proto_rawDesc), len(file_predict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_predict_proto_goTypes,
		DependencyIndexes: file_predict_proto_depIdxs,
		MessageInfos:      file_predict_proto_msgTypes,
	}.Build()
	File_predict_proto = out.File
	file_predict_proto_goTypes = nil
	file_predict_proto_depIdxs = nil
}
