# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\xb9\x01\n\x0ePredictRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x15\n\rmodel_version\x18\x03 \x01(\t\x12\x39\n\x08\x66\x65\x61tures\x18\x04 \x03(\x0b\x32\'.inference.PredictRequest.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x8e\x01\n\x0fPredictResponse\x12\x15\n\rprediction_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x15\n\rmodel_version\x18\x03 \x01(\t\x12\x12\n\nprediction\x18\x04 \x01(\x05\x12\x13\n\x0bprobability\x18\x05 \x01(\x01\x12\x12\n\nlatency_ms\x18\x06 \x01(\x01\"%\n\rHealthRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x98\x01\n\x10InferenceService\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\x12\x42\n\x0bHealthCheck\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseBCZAgithub.com/anand-exe7/DriftLine-MLOps/proto/inference;inferencepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/anand-exe7/DriftLine-MLOps/proto/inference;inferencepb'
  _globals['_PREDICTREQUEST_FEATURESENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=31
  _globals['_PREDICTREQUEST']._serialized_end=216
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_start=169
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_end=216
  _globals['_PREDICTRESPONSE']._serialized_start=219
  _globals['_PREDICTRESPONSE']._serialized_end=361
  _globals['_HEALTHREQUEST']._serialized_start=363
  _globals['_HEALTHREQUEST']._serialized_end=400
  _globals['_HEALTHRESPONSE']._serialized_start=402
  _globals['_HEALTHRESPONSE']._serialized_end=434
  _globals['_INFERENCESERVICE']._serialized_start=437
  _globals['_INFERENCESERVICE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
