syntax = "proto3";

package inference;

option go_package = "github.com/anand-exe7/DriftLine-MLOps/proto/inference;inferencepb";

service InferenceService {
  rpc Predict (PredictRequest) returns (PredictResponse);
  rpc HealthCheck (HealthRequest) returns (HealthResponse);
}

message PredictRequest {
  string request_id = 1;
  string model_id = 2;
  string model_version = 3;
  map<string, double> features = 4;
}

message PredictResponse {
  string prediction_id = 1;
  string model_id = 2;
  string model_version = 3;
  int32 prediction = 4;
  double probability = 5;
  double latency_ms = 6;
}

message HealthRequest {
  string service_name = 1;
}

message HealthResponse {
  string status = 1;
}
